<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>FreeLook</RootNamespace>
    <AssemblyName>FreeLook</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <DebugType>none</DebugType>
    <NoWarn>$(NoWarn);CS0649;CS0169</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Waltz.Modding.TLD.Il2CppAssemblies.Windows" Version="2.52.0" />
    <PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
  </ItemGroup>

</Project>
